### ISSUE TITLE
auto hunting use item

### ISSUE THREAD

**Issue by Psixxo** [L2jOrg/L2jOrg#31]
During auto hunting, if you use an item from your inventory, the item disappears and is not used.

**Comment by Forcecat01** [comment]
It often happens if you use items while reading a skill, or during an attack, items that you are trying to use disappear into the empty space. 

![3](https://user-images.githubusercontent.com/54755997/110342476-7d173c80-803c-11eb-87d3-544b70acde7f.gif)

if put on the panel and turned on, it uses more normally

**Comment by UchihaSV** [comment]
Yes, need add check using item conditions(to avoid disappear) from inventory while autohunt ON.

**Comment by Psixxo** [comment]
What about for this bugs?

**Comment by vicochips** [comment]
Hi , just need to change item xml` <attributes weight="5" immediate-effect="true" action="SKILL_REDUCE" auto-use="SUPPLY"/>`

to 

`<attributes weight="5" immediate-effect="true" action="SKILL_REDUCE_ON_SKILL_SUCCESS" auto-use="SUPPLY"/>`

**Comment by Psixxo** [comment]
in all item need change?

**Comment by Psixxo** [comment]
It is necessary to add a check, or put a ban on the use of items from the inventory during an attack or use of a skill.

**Comment by Psixxo** [comment]
The problem is not only in one thing that is shown in the gif. But in other subjects too.

**Comment by JoeAlisson** [comment]
Will be addressed in #57
