### ISSUE TITLE
AutoHunting 

### ISSUE THREAD

**Issue by Psixxo** [L2jOrg/L2jOrg#34]
If the roots are crushing on you, autoboy does not work. (Doesn't hit, targets change all the rules, but doesn't hit) Prof. Mage Or a ranged attack.

**Comment by JoeAlisson** [comment]
Sorry, I can't understand you. Can you explain better how I can reproduce it ?

**Comment by Forcecat01** [comment]
> Sorry, I can't understand you. Can you explain better how I can reproduce it ?

When standing at the roots, any debuff that holds. You cannot use ranged attacks until the debuff is gone

**Comment by Bru7aLMike** [comment]
That's because of the way DEBUFFs are handled. If I remember correctly, the
script currently puts all kinds of debuffs under the same group. The
easiest fix, imo, would be to add exceptions to the grand rule of how
debuffs are treated by auto-hunt.

На пн, 8.03.2021 г. в 7:57 ч. Forcecat <notifications@github.com> написа:

**Comment by Forcecat01** [comment]
did a couple of tests, noticed that while holding, long-range attacks work, with an auto shot, skill, ...

![4](https://user-images.githubusercontent.com/54755997/110332732-c615c380-8031-11eb-934f-422fa8d7043c.gif)
![1](https://user-images.githubusercontent.com/54755997/110332737-c7df8700-8031-11eb-8905-91474bb8337f.gif)
![2](https://user-images.githubusercontent.com/54755997/110332741-c8781d80-8031-11eb-9ab4-4bccd65154fb.gif)

**Comment by Bru7aLMike** [comment]
Yes, because manual input overwrites/bypasses the auto-hunt engine.

На пн, 8.03.2021 г. в 16:17 ч. Forcecat <notifications@github.com> написа:
